version: '3.8'

networks:
  serving_prod_net:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    volumes:
      - ./configurations/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus
    ports:
      - "9090:9090"  # Port accessible depuis l'extérieur pour Prometheus
    networks:
    - serving_prod_net


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8079:8080"  # Changement du port d'exposition pour cadvisor (port 8079 sur hôte)
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - serving_prod_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"  # Mot de passe admin par défaut, à changer
    ports:
      - "3000:3000"  # Port accessible depuis l'extérieur pour Grafana
    volumes:
      - ./data:/var/lib/grafana  # Mappage du dossier local monitoring/data vers le répertoire de données de Grafana
    networks:
      - serving_prod_net
